### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by coder543** [slide-rs/specs-website#3]
On [this line](https://github.com/slide-rs/specs-website/blob/gh-pages/docs/book/0.9/02_hello_world.html#L211), instead of hello world... we have hell world. A very unhappy place, I would imagine.

**Comment by torkleyy** [comment]
Thanks for reporting! Do you think you could create a PR for that? The relevant file would be in the book folder of the Specs repo, called `02_hello_world.md`.

**Comment by coder543** [comment]
I didn't realize where the relevant markdown file was, I've submitted a PR.

**Comment by torkleyy** [comment]
> I didn't realize where the relevant markdown file was

No problem, thanks for fixing!
